export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_SELECTED_PHOTO = 'SET_SELECTED_PHOTO';
export const SET_SIMILAR_PHOTOS = 'SET_SIMILAR_PHOTOS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_PHOTO_DATA = 'SET_PHOTO_DATA';
export const SET_TOPIC_DATA = 'SET_TOPIC_DATA';
