export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';
export const SET_SELECTED_PHOTO = 'SET_SELECTED_PHOTO';
export const SET_SIMILAR_PHOTOS = 'SET_SIMILAR_PHOTOS';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
